---
- name: Configuro servidor base de datos en ubuntu
  hosts: database
  become: true
  user: sysadmin

  tasks: 

  - name: UFW instalado
    ansible.builtin.apt:
      name: ufw
      state: present

  - name: Activar el puerto 22 en ufw
    community.general.ufw:
      rule: allow
      name: openSSH

  - name: Defino politicas de trafico
    community.general.ufw:
      policy: allow
      direction: outcoming
      state: enabled

  - name: Defino politicas de trafico
    community.general.ufw:
      policy: deny
      direction: incoming
      state: enabled

## Instalacion de base de datos
  - name: MariaDB instalado
    ansible.builtin.apt:
      name: mariadb-server
      state: present
      update-cache: true
    loop:
      - mariadb-server
      - mariadb-client
      - python3-pymysql

  - name: Cambiar la configuracion para escuchar en todas las interfaces
    ansible.builtin.libeinfile:
      path: /etc/mysqlmariadb.conf.d/50-servercnf
      regexp: '^bind-address'
      line: 'bind-address =0.0.0.0'
    


  - name: Servidor MariaDB levantado
    ansible.builtin.systemd_service:
      name: mariadb
      state: started
      enabled: true
  
  - name: Habilitamos en ufw la conexion a mariadb
    community.general.ufw:
      rule: allow
      port: '3306'
      protocol: tcp
      direction: in

## Configuracion de la base de datos

  - name: Creo la base de datos todo
    community.mysql.mysql_db:
      check_implicit_admin: true
      login_host: "{{ hostvars[inventory_hostname].ansible_host }}"
      login_user: root
      login_password: dbadmin
      name: todo
      state: import
      target: file/todo.sql
    delegate_to: localhost
    connection: local
     
  - name: servicio UFW levantado y habilitado
    ansible.builtin.systemd_service:
      name: ufw
      state: started
      enable: true


    